### ISSUE TITLE
How to use openai api?

### ISSUE THREAD

**Issue by 4t8dd** [huggingface/llm.nvim#106]
I read the code, and it seems support real openai api. But When I set it up something is wrong.
Just make sure if this supports open ai api? I mean realy openai api.

**Comment by 2nthony** [comment]
did you solved? same issue here.

**Comment by 4t8dd** [comment]
> did you solved? same issue here.

yes, I have fixed that in my fork. You can have a look at it.
It just used old api which is not supported now.

**Comment by 2nthony** [comment]
thanks, saw it. seems huggingface's openai api is different to origin openai 🤔
