### ISSUE TITLE
Could this plugin work with HuggingChat?

### ISSUE THREAD

**Issue by Haze-sh** [huggingface/llm.nvim#17]
I tried to change the model to the one used by huggingchat and it returns "Task not found for this model".

**Comment by McPatate** [comment]
It seems the model isn't hosted with the API inference, maybe because of some configuration issue.

I'd like to add a chat interface in the plugin to have a better UI to use these kinds of models, but I currently don't have the bandwidth to look into it.

**Comment by Haze-sh** [comment]
It is possible for this to use [model.nvim](https://github.com/gsuuon/model.nvim)
