### ISSUE TITLE
LLM Error: ['Stop'] not used

### ISSUE THREAD

**Issue by gdnaesver** [huggingface/llm.nvim#35]
Across multiple models (for example WizardLM/WizardCoder-1B-V1.0), both inference, using the model name and with my own depoyment I get the error:

[LLM] The following 'model_kwargs' are not used by the model: ['stop'] (note typos in the generate argument will also show up in this list)

I can't work out what to do to fix this....

**Comment by McPatate** [comment]
Hello @gdnaesver, I've recently changed the stop token parameter from `stop_token: "a string"` to `stop: ["a", "list", "of", "strings"]` and that may be it.

If you feel like fixing it feel free to submit a PR or I'll get to it at some later point.

**Comment by McPatate** [comment]
Here : https://github.com/huggingface/llm.nvim/blob/main/lua/llm/hf.lua#L40

**Comment by McPatate** [comment]
Do you have the full list of models for which you're having an error?

FYI, I've tested `WizardLM/WizardCoder-Python-34B-V1.0` and had no issues.

**Comment by McPatate** [comment]
So, transformers and TGI don't have the same API, `stop_tokens` for transformers & `stop` for TGI (api inference has workloads with both).

For now I'll just set the default to `nil` to not send anything, as there is, most of the time, a default EOS token.

I guess we could also infer EOS from the tokenizer file, but that's more something to implement in [llm-ls](https://github.com/huggingface/llm-ls).
