### ISSUE TITLE
Start with auto suggestion off

### ISSUE THREAD

**Issue by Dranaxel** [huggingface/llm.nvim#51]
Hello,

Thanks for this amazing plugin, starcoder is a blessing which was missing to my life ! Would it be possible to add an option to start with autosuggestion off so we can activate it when needed instead. My workflow is to bind `:LLMToggleAutoSuggest` to a shortcut like `HF` so I can toggle it at will, but a desactivated start would be more convenient

Thanks

**Comment by McPatate** [comment]
Glad that you like it!

I understand your need, would `disable_on_startup` configuration flag suit your needs?

I feel enabled by default makes more sense in general.
