### ISSUE TITLE
Add ability to specify file types to attach to.

### ISSUE THREAD

**Issue by dsully** [huggingface/llm.nvim#54]
Right now the llm-ls attaches to all file / buffer types, including things like the Telescope search field.

This plugin should implement a config option and functionality to only attach to specified file types like copilot.lua does:

https://github.com/zbirenbaum/copilot.lua/blob/master/lua/copilot/client.lua#L91

An example config would include:

```lua
filetypes = {
     bash = true,
     c = true,
     cpp = true,
     fish = true,
     go = true,
     html = true,
     java = true,
     javascript = true,
     just = true,
     lua = true,
     python = true,
     rust = true,
     sh = true,
     typescript = true,
     zsh = true,
     ["*"] = false, -- disable for all other filetypes and ignore default `filetypes`
}
```

Otherwise, something like this will happen:

![CleanShot 2023-09-29 at 07 02 29@2x](https://github.com/huggingface/llm.nvim/assets/22371/dff82d9e-0abd-48a5-92c8-9d72987047ff)

Thanks

**Comment by McPatate** [comment]
Check https://github.com/huggingface/llm.nvim/#suggestion-behavior and lmk if that works for you!
