### ISSUE TITLE
Large Models suuport: too large to be loaded automatically (67GB > 10GB)

### ISSUE THREAD

**Issue by aemonge** [huggingface/llm.nvim#69]
How can I use `WizardLM/WizardCoder-Python-34B-V1.0` or any other large module ?

**Comment by aemonge** [comment]
In case I go with either Spaces or Inference Endpoints, should I replace the string for the model, and use the endpoint direclty?

**Comment by McPatate** [comment]
Yes! It's either a model id from the Hugging Face Hub either an http url.
