### ISSUE TITLE
Error starting llm-ls

### ISSUE THREAD

**Issue by yduanBioinfo** [huggingface/llm.nvim#86]
I built llm-ls locally, and config it as following:
`  lsp = { 
    bin_path = "/home/myuser/soft/GPT/llm-ls-0.5.2/target/release/llm-ls",
    host = nil,
    port = nil,
    version = "0.5.2",
  },  
`
However, when opening nvim, I meet the Error starting llm-ls. And the nvim/lsp.log record:
`[START][2024-05-06 22:55:47] LSP logging initiated
[WARN][2024-05-06 22:55:47] .../lua/vim/lsp.lua:601     "buf_attach_client called on unloaded buffer (id: 1): "`

What should I do?
Thanks.

**Comment by jocelynthode** [comment]
I'm facing the same issue, were you able to resolve it? I imagine it's something to do with my other lsp configurations

**Comment by McPatate** [comment]
Lmk if updating the plugin works!

**Comment by jdonaldson** [comment]
Worked for me with a similar issue, regards!

**Comment by yduanBioinfo** [comment]
> Lmk if updating the plugin works!

It works! Thank you.
